server:
  port: 8070

spring:
  application:
    name: restaurants

  # MongoDB Configuration
  data:
    mongodb:
      uri: mongodb+srv://root:1234@fod-order.ngnx8j5.mongodb.net/
      database: fod-order
      username: root
      password: 1234

  config:
    import: optional:configserver:http://localhost:8888

stripe:
  api:
    key: 

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
